const getters = {
  sidebar: state => state.app.sidebar,
  size: state => state.app.size,
  device: state => state.app.device,
  visitedViews: state => state.tagsView.visitedViews,
  cachedViews: state => state.tagsView.cachedViews,
  token: state => state.user.token,
  avatar: state => state.user.avatar,
  name: state => state.user.name,
  nickName: state => state.user.nickName,
  introduction: state => state.user.introduction,
  roles: state => state.user.roles,
  permissions: state => state.user.permissions,
  permission_routes: state => state.permission.routes,
  mapMenuList: state => state.mapMenu.mapMenuList,
  typhoonUrl:state => state.config.typhoonUrl,
  detailComp: state => state.mapMenu.detailComp,
  cloudChartUrl:state =>state.config.cloudChartUrl,
  isInternal:state =>state.config.isInternal,
  myGroup:state => state.user.myGroup,
  myGroupAsLeader:state => state.user.myGroupAsLeader,
  user:state => state.user.user,
  monitorDataTypeList:state => state.dataMaintenance.monitorDataTypeList,
  statisticModel:state => state.statisticModel,
}
export default getters
